### PR TITLE
Updated README file

### PR DESCRIPTION
**Pull request by KPCOFGS**
## Fixes

Added LICENSE file. Added links to the LICENSE file that are also compatible to PyPI. Fixed the link to `example`

### CODE REVIEW

**Comment by kharigardner** [comment]
Appreciate cleaning some of this up 🙏🏽

**Review by KPCOFGS — COMMENTED** [review]
Updated README.md

**Comment by closerhan** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
Brennan-Richards, @kushalseth, @MahadevanAlagar1978, @jpt-la, @Marmoro, @MikeAinOz, @djg8813, @lz92at, @elpnt, @perceptionWave, @cyballnp1, @ToJen, @neerajp99, @rolodexter, @konbluesky, @terrificsoysauce, @Tym17, @peloni04, @abdul-maajid, @modulexcite, @choucrifahed, @mrjoedang, @Ginxo, @thomascherickal, @marikmuryn, @mpUrban, @yyusufaslan, @vulcangz, @hazard-pollack-baby, @Sharma-Hrishabh, @AbhiiGatty, @Timothysadera, @anshulahuja98, @mosasiru, @Donilo, @tkhemani, @webgurucan, @rodrigooler, @barvin04, @batmatt79, @Gunbae, @dpkbsmty, @temores, @keleffew, @exoticblockchains, @zhujun1980, @jdiss, @Web30ID, @Johnnie88, @stormfighter16

**Comment by closerhan** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!

**Pull request merged**
